### ISSUE TITLE
Typo in the code (uploaded wrong data to SLICED)

### ISSUE THREAD

**Issue by Asat108** [dgrtwo/data-screencasts#18]
https://github.com/dgrtwo/data-screencasts/blob/3c806ef0c678b3189643faa8b52d220f0e11ed18/ml-practice/board-games.Rmd#L398

Dear David,
There was a typo in the code. That's why the error with linear-reg and XGBoost was high on the Kaggle SLICED submission. 
write_csv(attempt1, "~/Desktop/attempt3.csv")

It should have been.
write_csv(attempt3, "~/Desktop/attempt3.csv")

**Comment by dgrtwo** [comment]
Oh wow! Thanks for catching this, it had been bothering me.

Upon this fix, that ensemble model out to have the best *private* score of the models I'd uploaded (the one based on 99% of the data). This makes sense since it had had the best performance on the holdout set I used. I think for next time I'll write a helper function for "evaluate on holdout" -> "add ID column" -> "write to file" to be less prone to typos like this.

![image](https://user-images.githubusercontent.com/994718/121192339-d7da5300-c83a-11eb-8952-5e5b192d66b4.png)

**Comment by Asat108** [comment]
Thank you very much for the excellent live coding session and then this solution for creating IDColumn to segregate predictions.
